In [1]:
import pandas as pd

df = pd.read_csv("final_dataset.csv")

df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MAX_DELAY,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,1,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,1,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0,0

In [2]:
df.shape

(36457, 20)

In [3]:
df['Approval_Status'] = df['TARGET'].map({
    0: "Approved",
    1: "Risky"
})

In [4]:
df['Approval_Status'].value_counts()

Approval_Status
Approved    35841
Risky         616
Name: count, dtype: int64

In [5]:
df['AGE'] = (df['DAYS_BIRTH'] / -365).astype(int)

In [6]:
df[['AGE','DAYS_BIRTH']].head()

   AGE  DAYS_BIRTH
0   32      -12005
1   32      -12005
2   58      -21474
3   52      -19110
4   52      -19110

In [7]:
df['EMPLOYMENT_YEARS'] = (df['DAYS_EMPLOYED'] / -365).astype(int)

In [8]:
dashboard_df = df[[
    'AGE',
    'AMT_INCOME_TOTAL',
    'NAME_INCOME_TYPE',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'CNT_CHILDREN',
    'CNT_FAM_MEMBERS',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'OCCUPATION_TYPE',
    'EMPLOYMENT_YEARS',
    'Approval_Status'
]]

In [9]:
dashboard_df.head()

,AGE,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,CNT_CHILDREN,CNT_FAM_MEMBERS,FLAG_OWN_CAR,FLAG_OWN_REALTY,OCCUPATION_TYPE,EMPLOYMENT_YEARS,Approval_Status
0,32,427500.0,Working,Higher education,Civil marriage,Rented apartment,0,2.0,Y,Y,NaN,12,Approved
1,32,427500.0,Working,Higher education,Civil marriage,Rented apartment,0,2.0,Y,Y,NaN,12,Approved
2,58,112500.0,Working,Secondary / secondary special,Married,House / apartment,0,2.0,Y,Y,Security staff,3,Approved
3,52,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1.0,N,Y,Sales staff,8,Approved
4,52,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1.0,N,Y,Sales staff,8,Approved

In [10]:
dashboard_df.to_csv("credit_risk_dashboard_dataset.csv", index=False)

In [11]:
dashboard_df.head()

,AGE,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,CNT_CHILDREN,CNT_FAM_MEMBERS,FLAG_OWN_CAR,FLAG_OWN_REALTY,OCCUPATION_TYPE,EMPLOYMENT_YEARS,Approval_Status
0,32,427500.0,Working,Higher education,Civil marriage,Rented apartment,0,2.0,Y,Y,NaN,12,Approved
1,32,427500.0,Working,Higher education,Civil marriage,Rented apartment,0,2.0,Y,Y,NaN,12,Approved
2,58,112500.0,Working,Secondary / secondary special,Married,House / apartment,0,2.0,Y,Y,Security staff,3,Approved
3,52,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1.0,N,Y,Sales staff,8,Approved
4,52,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,0,1.0,N,Y,Sales staff,8,Approved